// app/layout.js
import './globals.css';
import ContentPages from '@/components/ContentPages';

export const metadata = {
  title: 'Amazon',
  description: 'Generated by Amazon',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-hauora" >
        <ContentPages all={children} />
        </body>
    </html>
  );
}
